### ISSUE TITLE
trouble with entity comparison

### ISSUE THREAD

**Issue by Saereth** [TeamDman/ZenTriggers#4]
OK this is driving me nuts lol I cant seem to get the entity comparision to work correctly on the mighty ender chicken, but it DOES work correctly on just a normal chicken. Here are the 2 calls I'm using for testing:

```
Handler.onEntityUpdate(	
		PredicateBuilder.create()
			.isInBlock(<blockstate:animus:blockfluidantimatter>.block)
		,function(event as EntityLivingUpdateEvent){
		val message = "event triggered by entity" + event.entity.definition.name;
		print (message);
		val neutron = <avaritia:resource:2>;
		event.entity.world.spawnEntity(neutron.createEntityItem(event.entity.world, event.entity.position));
		event.entityLivingBase.health -= 5;
	}
);

Handler.onEntityUpdate(	
		PredicateBuilder.create()
			.isInstanceOf(<entity:mightyenderchicken:ent_EnderChicken>)
			.isInBlock(<blockstate:animus:blockfluidantimatter>.block)
		,function(event as EntityLivingUpdateEvent){
		print ("event triggered correctly");
		val neutron = <avaritia:resource:2>;
		event.entity.world.spawnEntity(neutron.createEntityItem(event.entity.world, event.entity.position));
		event.entityLivingBase.health -= 5;
	}
);
```

expected behavior:
I should see both messages printed in the logs for succeeding, ONLY the first message only shows up. also I tried changing the order of the scripts just to see if that made any difference, did not.

Log output from crafttweaker:

```
[SERVER_STARTED][CLIENT][INFO] event triggered by entityent_EnderChicken
[SERVER_STARTED][SERVER][INFO] event triggered by entityent_EnderChicken
[SERVER_STARTED][CLIENT][INFO] event triggered by entityent_EnderChicken
[SERVER_STARTED][CLIENT][INFO] event triggered by entityent_EnderChicken

```

so the script is seeing the entity's name correctly but the .isInstanceOf(<entity:mightyenderchicken:ent_EnderChicken>) check is never passing yet
.isInstanceOf(<entity:minecraft:chicken>) WILL successfully pass

this can be reproduced with these scripts and the minimal modlist 
zentriggers
crafttweaker
mightyender chicken 
animus
bloodmagic
avaritia

**Comment by TeamDman** [comment]
<entity:mightyenderchicken:ent_EnderChicken> fails to create a reference to the ender chicken in my dev instance
![image](https://user-images.githubusercontent.com/9356891/53907473-448e9380-401b-11e9-86fc-b5252838e2d2.png)

**Comment by TeamDman** [comment]
Fixed in https://github.com/TeamDman/ZenTriggers/commit/2177e5284e84d7479ec6f395964f8a172b426786
