### ISSUE TITLE
Replace mob

### ISSUE THREAD

**Issue by Pival81** [TeamDman/ZenTriggers#6]
Is there a way to replace mobs with others like exnihilo's witchwater does?
ExNihilo does it with the replaceMob() method on EntitySkeleton for replacing skeletons with witherskeletons, but I can't figure out a way to call that method from Zen Triggers

**Comment by TeamDman** [comment]
It would have to be done in the callback, there isn't a method in the mod to do it but you would be able to use any other zenmethods that may exist for entity manipulation
